### ISSUE TITLE
JMAP api routes not working

### ISSUE THREAD

**Issue by SurajDadral** [linagora/tmail-backend#383]
Hi There,

I am trying to get jmap working by following guide: https://github.com/linagora/tmail-backend/tree/master/tmail-backend/apps/distributed#with-docker-compose
After this, imap starts working fine. But, all web routes like: http://james.local/.well-known/jmap gives 404 not found.
Has anyone faced same issue before or any pointer if I am missing something?

Thanks,

**Comment by Arsnael** [comment]
Hello! 

I think you are missing something. What is the complete request you are sending for example to try to get the `.well-known/jmap` endpoint?

First of all don't try `james-local`... I think the hostname in docker-compose is somewhat buggy. Just try directly with `http://localhost/.well-known/jmap`

Second it might still say 404, because by default unfortunately for now we still have 2 jmap versions implemented. An early draft one, that is completely outdated but still used as the default as we have still a product depending on it.
And then the jmap rfc one, that is the implementation of the officialized RFC on it.

To pick up the right jmap version, you need to add an `Accept` header with this value: `application/json; jmapVersion=rfc-8621`

Then if you actually want to see a result (and not a 401) you need to create a user and add his creds in a basic auth header for example.

Then the endpoint after that that will interest you is likely `POST   http://localhost/jmap`

On an other side I just checked and there does not seem to be much documentation making that clear enough... That could be a point to raise

**Comment by SurajDadral** [comment]
Thanks @Arsnael 

After adding above suggested headers, it worked. I was missing `jmapVersion` header.
```
curl --location -X GET 'http://localhost/.well-known/jmap' --header 'Accept: application/json; jmapVersion=rfc-8621' --header 'Authorization: Basic YWxpY2VAbG9jYWxob3N0OmFsaWNlU2VjcmV0'
```

> On an other side I just checked and there does not seem to be much documentation making that clear enough... That could be a point to raise

Yes. That could be very helpful in long run.

Thanks,

**Comment by chibenwa** [comment]
There's also a way to configure the default JMAP version and make it rfc-8621 by default.

From my phone sry for not providing the exact prop. Ask of needed i'll look at it tmr.

Regards.
