### ISSUE TITLE
Review + improve our production deployments configuration

### ISSUE THREAD

**Issue by vttranlina** [linagora/tmail-backend#789]

**Comment by Arsnael** [comment]
I don't think it's necessary to spend more time on this... What I can conclude:

- not much can do to automate the release process on prod. Everything is released manually for tmail-backend, as we have some breaking changes sometimes (like cassandra table update, etc)
- I don't think a docker-compose is necessary and adds much to what we have already
- migrating to a new VM up to ddate, better security and support
- seems with Benoit we got accesses recently on cassandra and elasticsearch vms, which will make releases easier (had to spawn a docker cassandra from tmail vm before to connect to cassandra VMs remotely and do the job for example)
- discussions been going  on lately with hosting to remove the obm brick of prod, which will simplify our smtp flow, so that's good

**Comment by Arsnael** [comment]
Ah yes forgot a point as well:

- I think it would be better to deploy an elasticsearch v6 docker container on openpaas VM and point openpaas to it, as usage of indexing seems minimal it should be good enough... which would give us the opportunity to upgrade the elasticsearch nodes to opensearch and drop the backport of esv6 out of our tmail backend solution, making our deployments eassier (matching with preprod so battle tested before hand) and reducing technical debt and maintenance cost of our software too.

But well that's my 2 cents :)
